export type Project = {
  slug: string;
  title: string;
  client: string;
  year: string;
  category: string;
  summary: string;
  /** Two colours drive the case-study art block until real images exist. */
  colorFrom: string;
  colorTo: string;
  /** Ink colour used on top of the art block. */
  onColor: string;
  services: string[];
  stats: { value: string; label: string }[];
  sections: { heading: string; body: string }[];
  /** Drop a file in /public/work and put the path here to replace the colour block. */
  image?: string;
  featured?: boolean;
};

/**
 * ---------------------------------------------------------------------------
 * READ THIS BEFORE SHOWING THE SITE TO A CLIENT
 * ---------------------------------------------------------------------------
 * These case studies were drafted from the project folders on the Desktop, so
 * every claim traces back to something that is actually in those files — page
 * counts, the tech stack, the divisions of the business, the review checklist.
 *
 * Three kinds of gap are left for you, all marked in place:
 *
 *   TODO(year)   — I do not know when these shipped. Guessed years are worse
 *                  than no years; fix them.
 *   TODO(result) — every `value: "—"` stat. I will not invent numbers. Put in
 *                  something you can defend out loud, or delete the stat.
 *   TODO(check)  — a claim I inferred rather than read. Confirm or rewrite.
 *
 * Nothing here quotes a client, a contract, or a private file.
 * ---------------------------------------------------------------------------
 */
export const projects: Project[] = [
  {
    slug: "lobmeyr-venue",
    title: "Lobmeyr",
    client: "Lobmeyr", // TODO(check): the client's public-facing name
    year: "2025", // TODO(year)
    category: "Web Build & Code Audit",
    summary:
      "A premium wine and sake venue had a complete website generated by an AI tool and no way to judge whether it was safe to launch. I audited it end to end, fixed what production would have broken, and shipped it.",
    colorFrom: "#7a1028",
    colorTo: "#c9452f",
    onColor: "#f4efe4",
    services: ["Code audit", "Front-end build", "Performance & SEO", "Deployment"],
    stats: [
      { value: "13", label: "Pages taken to production" },
      { value: "8", label: "Audit areas covered" },
      { value: "—", label: "TODO(result): launch outcome" },
    ],
    sections: [
      {
        heading: "The problem",
        body: "The venue had a full React codebase produced by an AI tool. It looked finished, which is the dangerous part. Nobody on the client side could answer the questions that decide whether a site survives contact with real traffic: does the production build even pass, are there API keys sitting in the source, does it hold up on a phone, will it deploy anywhere other than the machine it was written on.",
      },
      {
        heading: "What I did",
        body: "I reviewed it against a fixed checklist rather than by feel — build integrity, responsive behaviour across iPhone, Android and tablet, component structure and dead code, image and render performance, title and meta and OGP and sitemap, hard-coded secrets and XSS exposure, and whether it could actually deploy to the host they intended to use. Then I fixed what the review turned up and finished the parts that were stubs: the thirteen pages covering the concept, floor plan, menu, events, performer profiles, recruitment and contact, plus the Express layer behind the contact form.",
      },
      {
        heading: "Why it mattered",
        body: "Generated code is now a normal starting point, and it is genuinely fast. What it does not come with is judgement about the last ten percent — the security, performance and deployment work that decides whether a site is publishable. That gap is the job. This project was a clean example of it.",
      },
    ],
    featured: true,
  },
  {
    slug: "morizo-corporate",
    title: "Morizo",
    client: "株式会社森蔵 / Morizo Co., Ltd.",
    year: "2025", // TODO(year)
    category: "Web Design & Build",
    summary:
      "A company running two unrelated businesses — food and beverage, and beauty — under one name, with no website that made the pairing look deliberate.",
    colorFrom: "#1d3a2f",
    colorTo: "#b98b3c",
    onColor: "#f4efe4",
    services: ["Web design", "Figma to React", "Front-end build", "Motion"],
    stats: [
      { value: "2", label: "Divisions under one identity" },
      { value: "—", label: "TODO(result): a number you can defend" },
      { value: "—", label: "TODO(result): or delete this stat" },
    ],
    sections: [
      {
        heading: "The problem",
        body: "Morizo operates a food and beverage division and a beauty division. Two audiences, two vocabularies, one company. Presented carelessly that reads as a business with no focus; presented well it reads as range. The site had to hold both without either half looking like an afterthought.",
      },
      {
        heading: "What I did",
        body: "Designed the site in Figma and then built it myself in React, so the layout and typography that were approved are the layout and typography that shipped — no interpretation step in between. A shared component layer keeps both divisions inside one visual system, with scroll-triggered motion used to pace the page rather than to decorate it.",
      },
      {
        heading: "The result",
        body: "TODO(result): what actually changed for them — enquiries, recruitment applications, how the two divisions are perceived. Write the sentence you could say to their face.",
      },
    ],
    featured: true,
  },
  {
    slug: "cero-securitytalk",
    title: "CERO SecurityTalk",
    client: "TODO(check): confirm how to name the client publicly",
    year: "2026", // TODO(year): first release
    category: "Brand Identity & Product",
    summary:
      "A security communication product that needed an identity and a working commercial platform at the same time — logo system, app icons, and the signup, payment and activation flow behind them.",
    colorFrom: "#0b2f7a",
    colorTo: "#3f8fd6",
    onColor: "#f4efe4",
    services: ["Brand identity", "App iconography", "Product design", "Front-end build"],
    stats: [
      { value: "—", label: "TODO(result): accounts, dealers, or scale" },
      { value: "—", label: "TODO(result): time from brand to launch" },
      { value: "—", label: "TODO(result): something measurable" },
    ],
    sections: [
      {
        heading: "The problem",
        body: "A new product being taken to market through dealers needed to look established before it had any track record, and it needed the commercial machinery to sell itself — accounts, payment, activation — running at the same time. Brand and product could not be sequenced one after the other.",
      },
      {
        heading: "What I did",
        body: "Built the identity as a system rather than a single mark: primary logo, reversed treatment for dark and light grounds, a defined palette, and separate application icons drawn to stay legible at small sizes. Then designed and built the customer-facing side of the platform — the flow from signup through payment to an active account — so the interface carried the same identity all the way through instead of stopping at the marketing page.",
      },
      {
        heading: "Why it mattered",
        body: "A dealer network sells what it can explain. When the logo, the portal and the emails all behave like one product, the person selling it does not have to apologise for anything. TODO(result): add what the business actually saw.",
      },
    ],
    featured: true,
  },
  {
    slug: "promofy-identity",
    title: "Promofy",
    client: "TODO(check): client name",
    year: "2024", // TODO(year)
    category: "Brand Identity",
    summary:
      "TODO(check): I only had the logo artwork for this one — no brief, no notes. Two or three sentences from you on what the company does and what the identity had to achieve.",
    colorFrom: "#ff3b14",
    colorTo: "#b5179e",
    onColor: "#f4efe4",
    services: ["Logo design", "Identity system"],
    stats: [
      { value: "—", label: "TODO(result)" },
      { value: "—", label: "TODO(result)" },
      { value: "—", label: "TODO(result)" },
    ],
    sections: [
      {
        heading: "The problem",
        body: "TODO(check): what was wrong, missing, or being launched.",
      },
      {
        heading: "What I did",
        body: "TODO(check): the decisions you made and why.",
      },
      {
        heading: "The result",
        body: "TODO(result): what changed.",
      },
    ],
  },
];

export const featuredProjects = projects.filter((p) => p.featured);

export function getProject(slug: string) {
  return projects.find((p) => p.slug === slug);
}
