export type Project = {
  slug: string;
  title: string;
  client: string;
  year: string;
  category: string;
  summary: string;
  /** Two colours drive the case-study art block until real images exist. */
  colorFrom: string;
  colorTo: string;
  /** Ink colour used on top of the art block. */
  onColor: string;
  services: string[];
  stats: { value: string; label: string }[];
  sections: { heading: string; body: string }[];
  /** Drop a file in /public/work and put the path here to replace the colour block. */
  image?: string;
  featured?: boolean;
};

/**
 * Published case studies. One real project beats four half-written ones, so
 * only finished entries live here.
 *
 * Morizo, CERO and Promofy are parked in `projects.drafts.ts` until their
 * dates and outcomes are settled. That file is imported by nothing.
 *
 * Every number below traces to something in the project folder: the page
 * count is the files in client/src/pages, the eight review areas are the
 * headings of the client's own check list, the three device classes are the
 * ones that list names.
 */
export const projects: Project[] = [
  {
    slug: "lobmeyr-venue",
    title: "Lobmeyr",
    client: "Lobmeyr",
    year: "2026",
    category: "Web Build & Code Audit",
    summary:
      "A premium wine and sake venue had its entire website generated by an AI tool, and no way to tell whether it was safe to launch. I reviewed it against the questions that actually decide that, fixed what production would have broken, and took the thirteen pages live.",
    colorFrom: "#7a1028",
    colorTo: "#c9452f",
    onColor: "#f4efe4",
    services: [
      "Code audit",
      "Front-end build",
      "Performance & SEO",
      "Logo & favicon",
      "Deployment",
    ],
    stats: [
      { value: "13", label: "Pages taken to production" },
      { value: "8", label: "Review areas covered" },
      { value: "3", label: "Device classes verified" },
    ],
    sections: [
      {
        heading: "The brief",
        body: "The client arrived with a complete React codebase produced by an AI tool and a single question: can this go live? That is a harder question than it sounds. Generated code looks finished — which is the dangerous part. It had never been checked for the things that decide whether a site survives contact with real traffic.",
      },
      {
        heading: "The audit",
        body: "I worked through it against a fixed list rather than by feel, because judging generated code on how it looks is exactly the trap. Eight areas: whether the production build passes and what it drags in, how the layout holds on iPhone, Android and tablet, whether components were separated or copy-pasted and what was dead, image weight and wasted renders, the SEO surface — title, meta, OGP, favicon, sitemap, structured data, then hard-coded API keys and XSS exposure, whether it could deploy anywhere other than the machine it was written on, and which parts were dummy data or forms pointing at nothing.",
      },
      {
        heading: "The build",
        body: "Then I fixed what the review turned up and finished what was scaffolding. Thirteen pages went to production — the venue concept and company profile, the floor plan, the menu, an events section with individual event pages, performer profiles, recruitment and contact — on React 19, Vite, Tailwind and TypeScript, with an Express layer behind the contact form and a theme context so the dark treatment behaves rather than half-applying. I drew the logo and favicon in the same stretch, so the mark and the site were decided together instead of one being fitted to the other.",
      },
      {
        heading: "Why this is the interesting one",
        body: "Generated code is now a normal starting point, and it is genuinely fast. What it does not come with is judgement about the last ten percent — the security, performance and deployment work that separates something that renders from something publishable. Increasingly that gap is the job, and it needs someone who can read the code and design the thing. This project was a clean example of both.",
      },
    ],
    featured: true,
  },
];

export const featuredProjects = projects.filter((p) => p.featured);

export function getProject(slug: string) {
  return projects.find((p) => p.slug === slug);
}
