export type Project = {
  slug: string;
  title: string;
  client: string;
  year: string;
  category: string;
  summary: string;
  /** Two colours drive the case-study art block until real images exist. */
  colorFrom: string;
  colorTo: string;
  /** Ink colour used on top of the art block. */
  onColor: string;
  services: string[];
  stats: { value: string; label: string }[];
  sections: { heading: string; body: string }[];
  /** Drop a file in /public/work and put the path here to replace the colour block. */
  image?: string;
  featured?: boolean;
};

/**
 * Published case studies. One real project beats four half-written ones, so
 * only finished entries live here.
 *
 * CERO and Promofy are parked in `projects.drafts.ts` until their dates and
 * outcomes are settled. That file is imported by nothing.
 *
 * Every number here traces to something in the project folder — page and
 * section counts are the actual files, the review areas are the headings of
 * the client's own check list, the brand and language counts are what the
 * content data contains. Nothing is estimated.
 */
export const projects: Project[] = [
  {
    slug: "lobmeyr-venue",
    title: "Lobmeyr",
    client: "Lobmeyr",
    year: "2026",
    category: "Web Build & Code Audit",
    summary:
      "A premium wine and sake venue had its entire website generated by an AI tool, and no way to tell whether it was safe to launch. I reviewed it against the questions that actually decide that, fixed what production would have broken, and took the thirteen pages live.",
    colorFrom: "#7a1028",
    colorTo: "#c9452f",
    onColor: "#f4efe4",
    services: [
      "Code audit",
      "Front-end build",
      "Performance & SEO",
      "Logo & favicon",
      "Deployment",
    ],
    stats: [
      { value: "13", label: "Pages taken to production" },
      { value: "8", label: "Review areas covered" },
      { value: "3", label: "Device classes verified" },
    ],
    sections: [
      {
        heading: "The brief",
        body: "The client arrived with a complete React codebase produced by an AI tool and a single question: can this go live? That is a harder question than it sounds. Generated code looks finished — which is the dangerous part. It had never been checked for the things that decide whether a site survives contact with real traffic.",
      },
      {
        heading: "The audit",
        body: "I worked through it against a fixed list rather than by feel, because judging generated code on how it looks is exactly the trap. Eight areas: whether the production build passes and what it drags in, how the layout holds on iPhone, Android and tablet, whether components were separated or copy-pasted and what was dead, image weight and wasted renders, the SEO surface — title, meta, OGP, favicon, sitemap, structured data, then hard-coded API keys and XSS exposure, whether it could deploy anywhere other than the machine it was written on, and which parts were dummy data or forms pointing at nothing.",
      },
      {
        heading: "The build",
        body: "Then I fixed what the review turned up and finished what was scaffolding. Thirteen pages went to production — the venue concept and company profile, the floor plan, the menu, an events section with individual event pages, performer profiles, recruitment and contact — on React 19, Vite, Tailwind and TypeScript, with an Express layer behind the contact form and a theme context so the dark treatment behaves rather than half-applying. I drew the logo and favicon in the same stretch, so the mark and the site were decided together instead of one being fitted to the other.",
      },
      {
        heading: "Why this is the interesting one",
        body: "Generated code is now a normal starting point, and it is genuinely fast. What it does not come with is judgement about the last ten percent — the security, performance and deployment work that separates something that renders from something publishable. Increasingly that gap is the job, and it needs someone who can read the code and design the thing. This project was a clean example of both.",
      },
    ],
    featured: true,
  },
  {
    slug: "morizo-group",
    title: "Morizo",
    client: "株式会社森蔵 / Morizo Co., Ltd.",
    year: "2026",
    category: "Web Design & Build",
    summary:
      "A holding company with three consumer brands across two unrelated industries, and a corporate site that made the group look like a filing error rather than a strategy. Rebuilt bilingual, from one content source.",
    colorFrom: "#1d3a2f",
    colorTo: "#b98b3c",
    onColor: "#f4efe4",
    services: [
      "Web design",
      "Bilingual content structure",
      "Front-end build",
      "Legacy migration",
    ],
    stats: [
      { value: "3", label: "Brands under one group" },
      { value: "2", label: "Languages, one content source" },
      { value: "9", label: "Page sections built" },
    ],
    sections: [
      {
        heading: "The problem",
        body: "Morizo runs three consumer brands across two industries that have nothing obvious in common — food and beverage on one side, beauty on the other. Presented without care that reads as a company with no focus. Presented well it reads as range. Their existing site was hand-written static HTML, CSS and a script file, and it had stopped being able to carry the story or be updated by anyone but a developer.",
      },
      {
        heading: "The structural decision",
        body: "The company operates in Japanese and needs to be legible in English, so language could not be an afterthought bolted on at the end. I put every string in a single content file and drove both languages from it through one language context. That is the decision the whole build rests on: adding or correcting copy is one edit in one place, in both languages, with no risk of the versions drifting apart — which is exactly what happens when a translation lives in a duplicated set of pages.",
      },
      {
        heading: "The build",
        body: "Designed the pages first, then built them myself in React and Vite so what was approved is what shipped. Nine sections carry the company: the opening, philosophy, a message from the representative director, the business divisions, the group brands, company information, access and contact. Scroll reveals pace the page rather than decorate it, and the contact flow uses a modal with proper toast feedback instead of dumping the visitor on a bare thank-you page. The old static site was retired into a legacy folder rather than deleted, so nothing was lost in the move.",
      },
      {
        heading: "Why it works",
        body: "The site stops apologising for the shape of the business. Each brand gets its own room instead of being flattened into a list, the group frame explains why they sit together, and an English-speaking visitor gets the same argument as a Japanese one rather than a thinner translated version of it.",
      },
    ],
    featured: true,
  },
];

export const featuredProjects = projects.filter((p) => p.featured);

export function getProject(slug: string) {
  return projects.find((p) => p.slug === slug);
}
